# Generated by Django 3.1.7 on 2021-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bias_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
    ]
