# Generated by Django 3.1.7 on 2021-03-10 02:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bias_backend_app', '0002_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('bias', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
